### ISSUE TITLE
Dependency unavailable

### ISSUE THREAD

**Issue by no-chili** [sk3llo/whisper_ggml#1]
I tried to run the example, but it kept failing because ffmpeg-kit-ios-full-gpl couldn't be downloaded.
```
[!] Error installing ffmpeg-kit-ios-full-gpl
[!] /usr/bin/curl -f -L -o /var/folders/71/hwy97pzn3lvb46bcxlwgdhtm0000gn/T/d20250412-61553-3nboqe/file.zip https://github.com/arthenica/ffmpeg-kit/releases/download/v6.0/ffmpeg-kit-full-gpl-6.0-ios-xcframework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.15.2 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

```

**Comment by sk3llo** [comment]
Hi! On what platform are you trying to run the example? Also are you using simulator or real device?

**Comment by Wdestroier** [comment]
```yaml
dependency_overrides:
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/Sahad2701/ffmpeg_kit_flutter_full_gpl.git
      ref: flutter-upgrade/remove-v1-embedding
```
